<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            //1 Saudi Arabia
            ['name' => 'Tabuk', 'name_ar' => 'تبوك', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Riyadh', 'name_ar' => 'الرياض', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'At Taif', 'name_ar' => 'الطائف', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Makkah Al Mukarramah', 'name_ar' => 'مكة المكرمة', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hail', 'name_ar' => 'حائل', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Buraydah', 'name_ar' => 'بريدة', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Hufuf', 'name_ar' => 'الهفوف', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ad Dammam', 'name_ar' => 'الدمام', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Madinah Al Munawwarah', 'name_ar' => 'المدينة المنورة', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Abha', 'name_ar' => 'ابها', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jazan', 'name_ar' => 'جازان', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jeddah', 'name_ar' => 'جدة', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Majmaah', 'name_ar' => 'المجمعة', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Khubar', 'name_ar' => 'الخبر', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hafar Al Batin', 'name_ar' => 'حفر الباطن', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Khamis Mushayt', 'name_ar' => 'خميس مشيط', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ahad Rifaydah', 'name_ar' => 'احد رفيده', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Qatif', 'name_ar' => 'القطيف', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Unayzah', 'name_ar' => 'عنيزة', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Qaryat Al Ulya', 'name_ar' => 'قرية العليا', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Jubail', 'name_ar' => 'الجبيل', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'An Nuayriyah', 'name_ar' => 'النعيرية', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dhahran', 'name_ar' => 'الظهران', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Wajh', 'name_ar' => 'الوجه', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Buqayq', 'name_ar' => 'بقيق', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Az Zulfi', 'name_ar' => 'الزلفي', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Khaybar', 'name_ar' => 'خيبر', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Ghat', 'name_ar' => 'الغاط', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Umluj', 'name_ar' => 'املج', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rabigh', 'name_ar' => 'رابغ', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Afif', 'name_ar' => 'عفيف', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thadiq', 'name_ar' => 'ثادق', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sayhat', 'name_ar' => 'سيهات', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tarut', 'name_ar' => 'تاروت', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Yanbu', 'name_ar' => 'ينبع', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Shaqra', 'name_ar' => 'شقراء', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ad Duwadimi', 'name_ar' => 'الدوادمي', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ad Diriyah', 'name_ar' => 'الدرعية', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quwayiyah', 'name_ar' => 'القويعية', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Muzahimiyah', 'name_ar' => 'المزاحمية', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Badr', 'name_ar' => 'بدر', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Kharj', 'name_ar' => 'الخرج', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ad Dilam', 'name_ar' => 'الدلم', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ash Shinan', 'name_ar' => 'الشنان', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Khurmah', 'name_ar' => 'الخرمة', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Jumum', 'name_ar' => 'الجموم', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Majardah', 'name_ar' => 'المجاردة', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'As Sulayyil', 'name_ar' => 'السليل', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tathilith', 'name_ar' => 'تثليث', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bishah', 'name_ar' => 'بيشة', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Baha', 'name_ar' => 'الباحة', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Qunfidhah', 'name_ar' => 'القنفذة', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Muhayil', 'name_ar' => 'محايل', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thuwal', 'name_ar' => 'ثول', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Duba', 'name_ar' => 'ضبا', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Turbah', 'name_ar' => 'تربه', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Safwa', 'name_ar' => 'صفوى', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Inak', 'name_ar' => 'عنك', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Turaif', 'name_ar' => 'طريف', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Arar', 'name_ar' => 'عرعر', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Qurayyat', 'name_ar' => 'القريات', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sakaka', 'name_ar' => 'سكاكا', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rafha', 'name_ar' => 'رفحاء', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dawmat Al Jandal', 'name_ar' => 'دومة الجندل', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ar Rass', 'name_ar' => 'الرس', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Midhnab', 'name_ar' => 'المذنب', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Khafji', 'name_ar' => 'الخفجي', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Riyad Al Khabra', 'name_ar' => 'رياض الخبراء', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Badai', 'name_ar' => 'البدائع', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ras Tannurah', 'name_ar' => 'رأس تنورة', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Bukayriyah', 'name_ar' => 'البكيرية', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ash Shimasiyah', 'name_ar' => 'الشماسية', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Hariq', 'name_ar' => 'الحريق', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hawtat Bani Tamim', 'name_ar' => 'حوطة بني تميم', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Layla', 'name_ar' => 'ليلى', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Billasmar', 'name_ar' => 'بللسمر', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sharurah', 'name_ar' => 'شرورة', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Najran', 'name_ar' => 'نجران', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sabya', 'name_ar' => 'صبيا', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Abu Arish', 'name_ar' => 'ابو عريش', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Samtah', 'name_ar' => 'صامطة', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ahad Al Musarihah', 'name_ar' => 'احد المسارحة', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'King Abdullah Economic City', 'name_ar' => 'مدينة الملك عبدالله الاقتصادية', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],

            //2 Bahrain
            ['name' => 'Alkora', 'name_ar' => 'الكورة', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Salmabad', 'name_ar' => 'سلماباد', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Abu Saiba', 'name_ar' => 'أبو صيبع', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Capricorn', 'name_ar' => 'أبوقوة', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Umm Al Hassam', 'name_ar' => 'أم الحصم', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Musala', 'name_ar' => 'المصلى', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tubli', 'name_ar' => 'توبلي', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Barbar', 'name_ar' => 'باربار', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Budaiya', 'name_ar' => 'البديع', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Busaiteen', 'name_ar' => 'البسيتين', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Bukwara', 'name_ar' => 'البوكوارة', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Buhaira', 'name_ar' => 'البحير', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bani Jamra', 'name_ar' => 'بني جمرة', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Puri', 'name_ar' => 'بوري', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jabla Habashi', 'name_ar' => 'جبلة حبشي', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jad Alhaj', 'name_ar' => 'جد الحاج', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jad Hafas', 'name_ar' => 'جد حفص', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jad Ali', 'name_ar' => 'جد علي', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Girdab', 'name_ar' => 'جرداب', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hawar Islands', 'name_ar' => 'جزر حوار', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Jasra', 'name_ar' => 'الجسرة', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Juffair', 'name_ar' => 'الجفير', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pleural', 'name_ar' => 'الجنبية', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Janusan', 'name_ar' => 'جنوسان', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Atmosphere', 'name_ar' => 'جو', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Had', 'name_ar' => 'الحد', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hajjat', 'name_ar' => 'الحجيات', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Suit of the good servant', 'name_ar' => 'حلة العبد الصالح', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hoora', 'name_ar' => 'الحورة', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Busaiteen', 'name_ar' => 'البسيتين', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'AlKamis', 'name_ar' => 'الخميس', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Darkleb', 'name_ar' => 'داركليب', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Mantika Aldublumasia', 'name_ar' => 'المنطقة الدبلوماسية', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Drains', 'name_ar' => 'الدراز', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Damistan', 'name_ar' => 'دمستان', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Dor', 'name_ar' => 'الدور', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Dir', 'name_ar' => 'الدير', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Deiah', 'name_ar' => 'الديه', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ras Rman', 'name_ar' => 'رأس رمان', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Riffa (East)', 'name_ar' => 'الرفاع (الشرقي)', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Riffa (Western)', 'name_ar' => 'الرفاع (الغربي)', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Zallak', 'name_ar' => 'الزلاق', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Zinj', 'name_ar' => 'الزنج', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Sakkiah', 'name_ar' => 'السقيه', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sar', 'name_ar' => 'سار', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Eskan Sar', 'name_ar' => 'اسكان سار', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Safera', 'name_ar' => 'سافرة', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Setra', 'name_ar' => 'سترة', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Samaheej', 'name_ar' => 'سماهيج', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sanabis', 'name_ar' => 'السنابس', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sanad', 'name_ar' => 'سند', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sahla (North and South)', 'name_ar' => 'السهلة (الشمالية والجنوبية)', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Seef suburb', 'name_ar' => 'ضاحية السيف', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Shakhoora', 'name_ar' => 'الشاخورة', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Shahrkan', 'name_ar' => 'شهركان', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sakhir', 'name_ar' => 'الصخير', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Saleheiah', 'name_ar' => 'الصالحيه', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sadad', 'name_ar' => 'صدد', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Aali', 'name_ar' => 'عالي', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Adliya', 'name_ar' => 'العدلية', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Azari', 'name_ar' => 'عذاري', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Arad', 'name_ar' => 'عراد', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Askar', 'name_ar' => 'عسكر', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Aker', 'name_ar' => 'العكر', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Awali', 'name_ar' => 'عوالي', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ayn Aldar', 'name_ar' => 'عين الدار', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Kadam', 'name_ar' => 'القدم', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Karia', 'name_ar' => 'القرية', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Kadebiah', 'name_ar' => 'القضيبية', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kalalli', 'name_ar' => 'قلالي', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Kalaa', 'name_ar' => 'القلعة', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Karana', 'name_ar' => 'كرانة', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Hajar', 'name_ar' => 'الحجر', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Karbabad', 'name_ar' => 'كرباباد', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Karzakan', 'name_ar' => 'كرزكان', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mahooz', 'name_ar' => 'الماحوز', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Maliki', 'name_ar' => 'المالكية', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hamad town', 'name_ar' => 'مدينة حمد', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Zayed town', 'name_ar' => 'مدينة زايد', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Isa Town', 'name_ar' => 'مدينة عيسى', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Muharraq', 'name_ar' => 'المحرق', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ma\'ameer', 'name_ar' => 'المعامير', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mukabeh', 'name_ar' => 'مقابة', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mukasha', 'name_ar' => 'المقشع', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Manama', 'name_ar' => 'المنامة', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nabih Saleh', 'name_ar' => 'النبيه صالح', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Naeim', 'name_ar' => 'النعيم', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Nwaidarat', 'name_ar' => 'النويدرات', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hamala', 'name_ar' => 'الهملة', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],

            //3 Qatar
            ['name' => 'Doha', 'name_ar' => 'الدوحة', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Abu Al-Dhadouf', 'name_ar' => 'أبو الظلوف', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Abu Thaila', 'name_ar' => 'أبو ثايلة', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'New Doha', 'name_ar' => 'الدوحة الجديدة', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Arish', 'name_ar' => 'الـعريش', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Eastern fads', 'name_ar' => 'البدع الشرقية', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al-Ghunaim', 'name_ar' => 'الغنيم', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al-Gharia', 'name_ar' => 'الغارية', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'West Alhilal', 'name_ar' => 'الهلال الغربية', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'East Alhilal', 'name_ar' => 'الهلال الشرقية', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hitmi', 'name_ar' => 'الهتمي', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Jasra', 'name_ar' => 'الجسرة', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Jamiliah', 'name_ar' => 'الجميلية', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Kaaban', 'name_ar' => 'الكعبان', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Khalifah', 'name_ar' => 'الخليفة', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Khour', 'name_ar' => 'الخور', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Zakhera', 'name_ar' => 'الذخيرة', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Khawr', 'name_ar' => 'الخاور', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Khawair', 'name_ar' => 'الخواير', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Mafjar', 'name_ar' => 'الـمفجر', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Kabeah', 'name_ar' => 'القابية', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Wakrah', 'name_ar' => 'الوكرة', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'The second city', 'name_ar' => 'المدينة الثانية', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Azbah', 'name_ar' => 'العذبة', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Najmah', 'name_ar' => 'النجمة', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Rakis', 'name_ar' => 'الراكيات', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Rayyan', 'name_ar' => 'الريان', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Ruwais', 'name_ar' => 'الرويس', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al salatah', 'name_ar' => 'السالاتة', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al salatah Al jadidah', 'name_ar' => 'السلاتة الجديدة', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Sanniaa', 'name_ar' => 'الصنيع', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Souk', 'name_ar' => 'السوق', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Thukeb', 'name_ar' => 'الثقب', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dukhan', 'name_ar' => 'دخان', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Zekreet', 'name_ar' => 'زكريت', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ras Laffan Industrial City', 'name_ar' => 'مدينة رأس لفان الصناعية', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Umm Bab', 'name_ar' => 'أم باب', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mesaieed', 'name_ar' => 'مسيعيد', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Umm Salal Ali', 'name_ar' => 'أم صلال على', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Umm Salal Muhammad', 'name_ar' => 'أم صلال محمد', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Umm Ahwaiya', 'name_ar' => 'أم الاحويا', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Umm scrapes', 'name_ar' => 'أم الشخوط', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Umm Al Omed', 'name_ar' => 'أم العمد', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Umm Abiriya', 'name_ar' => 'أم عبيرية', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Asat Al Raie', 'name_ar' => 'عصاة الراعي', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hattan', 'name_ar' => 'حوطان', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Sakhameh', 'name_ar' => 'الصخامة', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Umm Algamagem', 'name_ar' => 'أم الجماجم', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Umm Al Afaie', 'name_ar' => 'أم الافاعي', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Umm Al Qhab', 'name_ar' => 'أم القهاب', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Umm Shibram', 'name_ar' => 'ام شبرم', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'McCaines', 'name_ar' => 'مكينس', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Khararh', 'name_ar' => 'الخرارة', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Shahaniya', 'name_ar' => 'الشحانية', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Jamiliah', 'name_ar' => 'الجميلية', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kharib', 'name_ar' => 'خريب', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Sunaa', 'name_ar' => 'الصنع', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Atoria', 'name_ar' => 'العطورية', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al-Ghuwayriyah', 'name_ar' => 'الغويرية', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Anemone', 'name_ar' => 'النعمان', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Zubarah', 'name_ar' => 'الزبارة', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Majeda', 'name_ar' => 'الماجدة', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Muhaish', 'name_ar' => 'محيش', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Reem', 'name_ar' => 'الريم', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Kaf', 'name_ar' => 'القاف', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Ghashmeiah', 'name_ar' => 'الغشامية', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Kaaban', 'name_ar' => 'الكعبان', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Waab', 'name_ar' => 'الوعب', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Foyert', 'name_ar' => 'فويرط', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Muroneh', 'name_ar' => 'المرونة', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Arida', 'name_ar' => 'عريدة', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ras Almatbakh', 'name_ar' => 'راس مطبخ', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Eye Asnan', 'name_ar' => 'عين اسنان', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rawdat Rashed', 'name_ar' => 'روضة راشد', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Alkanaah', 'name_ar' => 'الكرعانة', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ameria', 'name_ar' => 'العامرية', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Aouina', 'name_ar' => 'العوينة', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Wukair', 'name_ar' => 'الوكير', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Katar', 'name_ar' => 'قطر', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al seleiah', 'name_ar' => 'السيليه', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],

            //4 Kuwait
            ['name' => 'Capital', 'name_ar' => '    العاصمة', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ahmadi', 'name_ar' => '    الأحمدي', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Fardous', 'name_ar' => '    الفردوس', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Farwaniyah', 'name_ar' => '    الفروانية', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hawli', 'name_ar' => '    حولي', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jahra', 'name_ar' => '    الجهراء', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mubarak Al Kaber', 'name_ar' => '    مبارك الكبير', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],

            //5 United Arab Emirates
            ['name' => 'Dubai', 'name_ar' => 'دبي', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Abu Dhabi', 'name_ar' => 'أبوظبي', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sharjah', 'name_ar' => 'الشارقة', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Al Ain', 'name_ar' => 'العين', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ras Al Khaimah', 'name_ar' => 'رأس الخيمة', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ajman', 'name_ar' => 'عجمان', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Fujairah', 'name_ar' => 'الفجيرة', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Umm Al Quwain', 'name_ar' => 'أم القيوين', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Khorfakkan', 'name_ar' => 'خورفكان', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dibba Al-Hisn', 'name_ar' => 'دبا الحصن', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],

            //6 Oman
            ['name' => 'Maskat', 'name_ar' => 'مسقط', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Saham', 'name_ar' => 'صحم', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sohar', 'name_ar' => 'صحار', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Salalah', 'name_ar' => 'صلالة', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Seeb', 'name_ar' => 'السيب', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Abri', 'name_ar' => 'عبري', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nazwa', 'name_ar' => 'نزوى', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
        ];
        City::query()->insert($cities);
    }
}
