<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ['name' => 'Saudi Arabia', 'name_ar' => 'السعودية', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Syria', 'name_ar' => 'سوريا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lebanon', 'name_ar' => 'لبنان', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Afghanistan', 'name_ar' => 'أفغانستان', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Albania', 'name_ar' => 'ألبانيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Algeria', 'name_ar' => 'الجزائر', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Andorra', 'name_ar' => 'أندورا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Angola', 'name_ar' => 'أنجولا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Antigua & Barbuda', 'name_ar' => 'انتيجوا وباربودا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Argentina', 'name_ar' => 'الأرجنتين', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Armenia', 'name_ar' => 'أرمينيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Australia', 'name_ar' => 'استراليا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Austria', 'name_ar' => 'النمسا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Azerbaijan', 'name_ar' => 'أذربيجان', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'The Bahamas', 'name_ar' => 'جزر البهاما', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bahrain', 'name_ar' => 'البحرين', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bangladesh', 'name_ar' => 'بنجلاديش', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Barbados', 'name_ar' => 'باربادوس', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Belarus', 'name_ar' => 'بيلا روسيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Belgium', 'name_ar' => 'بلجيكا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Belize', 'name_ar' => 'بيليز', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Benin', 'name_ar' => 'بنين', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bhutan', 'name_ar' => 'بوتان', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bolivia', 'name_ar' => 'بوليفيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bosnia & Herzegovina', 'name_ar' => 'البوسنة والهرسك', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Botswana', 'name_ar' => 'بوتسوانا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Brazil', 'name_ar' => 'البرازيل', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Brunei', 'name_ar' => 'بروناى', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bulgaria', 'name_ar' => 'بلغاريا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Burkina Faso', 'name_ar' => 'بوركينا فاسو', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Burundi', 'name_ar' => 'بوروندى', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cambodia', 'name_ar' => 'كمبوديا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cameroon', 'name_ar' => 'الكاميرون', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Canada', 'name_ar' => 'كندا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cape Verde', 'name_ar' => 'الرأس الاخضر', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Central African Republic', 'name_ar' => 'جمهورية افريقيا الوسطى', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chad', 'name_ar' => 'تشاد', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chile', 'name_ar' => 'شيلى', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'China', 'name_ar' => 'الصين', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Colombia', 'name_ar' => 'كولمبيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Comoros', 'name_ar' => 'جزر الُقمـــر', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Republic of the Congo', 'name_ar' => 'جمهورية الكونغو', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Democratic Republic of the Congo', 'name_ar' => 'جمهورية الكونغو الديمقراطية', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Costa Rica', 'name_ar' => 'كوستاريكا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cote d’Ivoire', 'name_ar' => 'كوت ديفوار', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Croatia', 'name_ar' => 'كرواتيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cuba', 'name_ar' => 'كوبا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cyprus', 'name_ar' => 'قبرص', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CzechRepublic', 'name_ar' => 'جمهورية التشيك', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Denmark', 'name_ar' => 'الدنمارك', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Djibouti', 'name_ar' => 'جيبوتى', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dominica', 'name_ar' => 'دومينيكا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dominican Republic', 'name_ar' => 'الدومينيكان', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'East Timor', 'name_ar' => 'تيمور الشرقية', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ecuador', 'name_ar' => 'الأكوادور', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Egypt', 'name_ar' => 'مصر', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'El Salvador', 'name_ar' => 'السلفادور', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Equatorial Guinea', 'name_ar' => 'غينيا الأستوائية', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Eritrea', 'name_ar' => 'أريتريا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Estonia', 'name_ar' => 'أستونيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ethiopia', 'name_ar' => 'أثيوبيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Fiji', 'name_ar' => 'جزر فيجى', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Finland', 'name_ar' => 'فنلندا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'France', 'name_ar' => 'فرنسا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gabon', 'name_ar' => 'الجابون', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'The Gambia', 'name_ar' => 'جامبيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Georgia', 'name_ar' => 'جورجيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Germany', 'name_ar' => 'المانيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ghana', 'name_ar' => 'غانا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Greece', 'name_ar' => 'اليونان', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Grenada', 'name_ar' => 'جرانادا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Guatemala', 'name_ar' => 'جواتيمالا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Guinea', 'name_ar' => 'غينيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'GuineaBissau', 'name_ar' => 'غينيا بيساو', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Guyana', 'name_ar' => 'جويانا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Haiti', 'name_ar' => 'هايتى', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Honduras', 'name_ar' => 'هندوراس', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hungary', 'name_ar' => 'المجر', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Iceland', 'name_ar' => 'ايسلندا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'India', 'name_ar' => 'الهند', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Indonesia', 'name_ar' => 'إندونيسيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Iran', 'name_ar' => 'إيران', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Iraq', 'name_ar' => 'العراق', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ireland', 'name_ar' => 'إيرلندا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Philsten', 'name_ar' => 'فلسطين', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Italy', 'name_ar' => 'إيطاليا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jamaica', 'name_ar' => 'جاميكا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Japan', 'name_ar' => 'اليابان', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jordan', 'name_ar' => 'الأردن', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kazakhstan', 'name_ar' => 'كازاخستان', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kenya', 'name_ar' => 'كينيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kiribati', 'name_ar' => 'كيريباتى', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Korea, North', 'name_ar' => 'كوريا الشمالية', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Korea, South', 'name_ar' => 'كوريا الجنوبية', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kuwait', 'name_ar' => 'الكويت', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kyrgyzstan', 'name_ar' => 'قرغيزستان', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Laos', 'name_ar' => 'لاوس', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Latvia', 'name_ar' => 'لاتفيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lesotho', 'name_ar' => 'ليسوتو', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Liberia', 'name_ar' => 'ليبيريا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Libya', 'name_ar' => 'ليبيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Liechtenstein', 'name_ar' => 'ليختنشتاين', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lithuania', 'name_ar' => 'ليتوانيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Luxembourg', 'name_ar' => 'لوكسمبورج', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Macedonia', 'name_ar' => 'مقدونيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Madagascar', 'name_ar' => 'مدغشقر', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Malawi', 'name_ar' => 'مالاوى', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Malaysia', 'name_ar' => 'ماليزيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Maldives', 'name_ar' => 'جزر المالديف', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mali', 'name_ar' => 'مالى', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Malta', 'name_ar' => 'جزيرة مالطا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Marshall Islands', 'name_ar' => 'جزر مارشال', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mauritania', 'name_ar' => 'موريتانيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mauritius', 'name_ar' => 'موريشيوس', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mexico', 'name_ar' => 'المكسيك', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Federated States of Micronesia', 'name_ar' => 'جزر مايكرونيزيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Moldova', 'name_ar' => 'مولدوفيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Monaco', 'name_ar' => 'امارة موناكو', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mongolia', 'name_ar' => 'منغوليا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Montenegro', 'name_ar' => 'مونتنيجرو', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Morocco', 'name_ar' => 'المغرب', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mozambique', 'name_ar' => 'موزمبيق', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Myanmar (Burma)', 'name_ar' => 'ميانمار (بورما)', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Namibia', 'name_ar' => 'ناميبيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nauru', 'name_ar' => 'ناورو', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nepal', 'name_ar' => 'نيبال', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Netherlands', 'name_ar' => 'هولندا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'New Zealand', 'name_ar' => 'نيوزيلندا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nicaragua', 'name_ar' => 'نيكاراجوا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Niger', 'name_ar' => 'النيجر', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nigeria', 'name_ar' => 'نيجيريا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Norway', 'name_ar' => 'النرويج', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Oman', 'name_ar' => 'سلطنة عًمان', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pakistan', 'name_ar' => 'باكستان', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Palau', 'name_ar' => 'بالو', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Panama', 'name_ar' => 'بنما', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Papua New Guinea', 'name_ar' => 'بابوا غينيا الجديدة', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Paraguay', 'name_ar' => 'باراجوى', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Peru', 'name_ar' => 'بيرو', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Philippines', 'name_ar' => 'الفلبين', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Poland', 'name_ar' => 'بولندا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Portugal', 'name_ar' => 'البرتغال', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Qatar', 'name_ar' => 'قطر', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Romania', 'name_ar' => 'رومانيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Russia', 'name_ar' => 'روسيا الاتحادية', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rwanda', 'name_ar' => 'رواندا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Saint Kitts and Nevis', 'name_ar' => 'سان كيتس أند نيفز', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Saint Lucia', 'name_ar' => 'سان لوتشيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Saint Vincent and the Grenadines', 'name_ar' => 'سان فنسن وجرينادينز', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Samoa', 'name_ar' => 'ساموا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'San Marino', 'name_ar' => 'سان مارينو', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sao Tome and Principe', 'name_ar' => 'ساوتومى أند برنسيب', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Senegal', 'name_ar' => 'السنغال', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Serbia', 'name_ar' => 'صربيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Seychelles', 'name_ar' => 'جزر سيشل', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sierra Leone', 'name_ar' => 'سيراليون', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Singapore', 'name_ar' => 'سنغافورة', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Slovakia', 'name_ar' => 'سلوفاكيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Slovenia', 'name_ar' => 'سلوفينيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Solomon Islands', 'name_ar' => 'جزر سولومون', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Somalia', 'name_ar' => 'الصومال', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'South Africa', 'name_ar' => 'جنوب افريقيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Spain', 'name_ar' => 'إسبانيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sri Lanka', 'name_ar' => 'سريلانكا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sudan', 'name_ar' => 'السودان', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Suriname', 'name_ar' => 'سورينام', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Swaziland', 'name_ar' => 'سوازيلاند', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sweden', 'name_ar' => 'السويد', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Switzerland', 'name_ar' => 'سويسرا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tajikistan', 'name_ar' => 'طاجكستان', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tanzania', 'name_ar' => 'تنزانيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thailand', 'name_ar' => 'تايلاند', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Togo', 'name_ar' => 'توجو', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tonga', 'name_ar' => 'تونجا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trinidad and Tobago', 'name_ar' => 'ترينداد وتوباغو', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tunisia', 'name_ar' => 'تــــوِنس', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Turkey', 'name_ar' => 'تركيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Turkmenistan', 'name_ar' => 'تركمانستان', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tuvalu', 'name_ar' => 'توفالو', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Uganda', 'name_ar' => 'أوغندا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ukraine', 'name_ar' => 'أوكرانيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'United Arab Emirates', 'name_ar' => 'الإمارات العربية المتحدة', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'United Kingdom', 'name_ar' => 'المملكة المتحدة', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'United States', 'name_ar' => 'الولايات المتحدة الأمريكية', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Uruguay', 'name_ar' => 'أورجواى', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Uzbekistan', 'name_ar' => 'أوزباكستان', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vanuatu', 'name_ar' => 'فانواتو', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vatican City(Holy Seed)', 'name_ar' => 'الفاتيكان', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Venezuela', 'name_ar' => 'فنزويلا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vietnam', 'name_ar' => 'فيتنام', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Yemen', 'name_ar' => 'اليمن', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Zambia', 'name_ar' => 'زامبيا', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Zimbabwe', 'name_ar' => 'زيمبابوى', 'created_at' => now(), 'updated_at' => now()],

        ];
        Country::query()->insert($countries);
    }
}
